Lab18ConsumeApi/Models/ToDoList.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Lab18ConsumeApi.Models
{
    public class ToDoList
    {
        public int ID { get; set; }
        [Required]
        public string Name { get; set; }
        public IEnumerable<ToDoItem> ToDoItems { get; set; }
        [Required]
        public bool IsDone { get; set; }
    }
}

Lab18ConsumeApi/Controllers/ToDoListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using Lab18ConsumeApi.Models;
using Microsoft.AspNetCore.Mvc;

namespace Lab18ConsumeApi.Controllers
{
    public class ToDoListController : Controller
    {
        /// <summary>
        /// Action to just grab a View
        /// </summary>
        /// <returns>A View</returns>
        [HttpGet]
        public IActionResult Create() => View();
        /// <summary>
        /// Action that uses a POST to create a new ToDoList to send to the API.
        /// </summary>
        /// <param name="toDoList">ToDoList objce</param>
        /// <returns>Redirect to Index on the Home controller or reload create view</returns>
        [HttpPost]
        public async Task<IActionResult> Create([Bind("ID,Name,IsDone")]ToDoList toDoList)
        {
            if (ModelState.IsValid)
            {
                await APIListPost(toDoList);
                return RedirectToAction("Index","Home");
            }
            return View();
        }
        /// <summary>
        /// Action that uses a GET request to grab the specific ToDoList from the API
        /// with its id
        /// </summary>
        /// <param name="id">id of ToDoList Object</param>
        /// <returns>A view passed with  ListsViewModel or Redirect to Index on the Home Controller</returns>
        [HttpGet]
        public async Task<IActionResult> Details(long? id)
        {
            if (id.HasValue)
            {
                return View(ListsViewModel.GetAList(id.Value, await APIListGetOne(id.Value)));
            }
            return RedirectToAction("Index", "Home");
        }
        /// <summary>
        /// Action that uses a GET to grab the id of ToDoList to confirm deletion
        /// </summary>
        /// <param name="id">id of ToDoList object</param>
        /// <returns>Confirm Delete View or a redirect if no id value</returns>
        [HttpGet]
        public async Task<IActionResult> Delete(long? id)
        {
            if (id.HasValue)
            {
                return View(ListsViewModel.GetAList(id.Value, await APIListGetOne(id.Value)));
            }
            return RedirectToAction("Index", "Home");
        }
        /// <summary>
        /// Action to update the current ToDoList object and use a PUT
        /// request to the API
        /// </summary>
        /// <param name="id">id of current ToDoList object</param>
        /// <param name="list">ToDoList object</param>
        /// <returns>Redirect to index on the home controller or reload page if ModelState is not valid</returns>
        [HttpPost]
        public async Task<IActionResult> Update(long id, [Bind("ID,Name,IsDone")]ToDoList list)
        {
            ListsViewModel lvm = ListsViewModel.GetAList(id, await APIListGetOne(id));
            if (ModelState.IsValid)
            {
                list.ID = (int)id;
                await APIListPut(id,list);
                return RedirectToAction("Index", "Home");
            }
            return View(ListsViewModel.GetAList(id, await APIListGetOne(id)));
        }
        /// <summary>
        /// Action that uses a DELETE request to remove the specific ToDoList object from the
        /// API
        /// </summary>
        /// <param name="id">id of ToDoList object</param>
        /// <returns>
        /// Redirect to a view if user attempts to remove the default list, 
        /// else Deletes list and all tasks with list
        /// </returns>
        [HttpPost]
        public async Task<IActionResult> Delete(long id)
        {
            if(id == 1)
            {
                return RedirectToAction("DeleteDefault");
            }
            await APItodoListDelete(id);
            return RedirectToAction("Index", "Home");
        }
        /// <summary>
        /// Action for the Default List Delete catch
        /// </summary>
        /// <returns>View</returns>
        [HttpGet]
        public IActionResult DeleteDefault() => View();
        /// <summary>
        /// Action that makes a POST call to the API to create a new List
        /// </summary>
        /// <param name="list">ToDoList object</param>
        /// <returns>Status code</returns>
        public async Task<HttpStatusCode> APIListPost(ToDoList list)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://eisj-todoapi.azurewebsites.net");
                var response = await client.PostAsJsonAsync("/api/todolist", list);
                return response.StatusCode;
            }
        }
        /// <summary>
        /// Action that uses a GET to the API to retrieve a specific ToDoList
        /// </summary>
        /// <param name="id">ToDoList object ID</param>
        /// <returns>JSON string</returns>
        public async Task<string> APIListGetOne(long? id)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://eisj-todoapi.azurewebsites.net");
                var response = client.GetAsync($"/api/todolist/{id.Value}").Result;

                if (response.EnsureSuccessStatusCode().IsSuccessStatusCode)
                {
                    string todolistResult = await response.Content.ReadAsStringAsync();
                    return todolistResult;
                }
                return "";
            }
        }
        /// <summary>
        /// Action that makes a PUT request to the API to update the current
        /// ToDoList or create a new one
        /// </summary>
        /// <param name="id">Id of the ToDoList object</param>
        /// <param name="list">ToDoList object</param>
        /// <returns>Status code</returns>
        public async Task<HttpStatusCode> APIListPut(long id, ToDoList list)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://eisj-todoapi.azurewebsites.net");
                var response = await client.PutAsJsonAsync($"/api/todolist/{id}", list);
                return response.StatusCode;
            }
        }
        /// <summary>
        /// Action that makes a DELETE request to the API based on the specific
        /// ToDoList id
        /// </summary>
        /// <param name="id">ID of a specific ToDoList objec</param>
        /// <returns>JSON string</returns>
        public async Task<string> APItodoListDelete(long? id)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://eisj-todoapi.azurewebsites.net");
                var response = client.DeleteAsync($"/api/todolist/{id.Value}").Result;

                if (response.EnsureSuccessStatusCode().IsSuccessStatusCode)
                {
                    string todoItemResult = await response.Content.ReadAsStringAsync();
                    return todoItemResult;
                }
                return "";
            }
        }
    }
}

Lab18ConsumeApi/Views/ToDoList/Create.cshtml
@model Lab18ConsumeApi.Models.ToDoList

<div class="wrapper">
    <h1>Make a new List</h1>
    <form method="post" asp-controller="ToDoList" form-action="Create">
        <table>
            <tr>
                <td>
                    <label asp-for="Name">Name</label>
                </td>
                <td>
                    <input asp-for="Name" />
                </td>
            </tr>
            <tr>
                <td>
                    <label asp-for="IsDone">Is it done?</label>
                </td>
                <td>
                    <input type="checkbox" asp-for="IsDone" />
                </td>
            </tr>
        </table>

        <button type="submit">Make List</button>
        <a class="home" asp-controller="Home" asp-action="Index">return to Lists</a>
    </form>
</div>

Lab18ConsumeApi/Views/ToDoList/Delete.cshtml
@model Lab18ConsumeApi.Models.ListsViewModel

<div class="wrapper">
    <h2>Are you sure you want to delete this list?</h2>
    <p>All tasks with this list will be deleted!</p>

    <form asp-action="Delete">
        <input type="hidden" asp-for="List.ID" />
        <input type="submit" value="Delete" />
        <a asp-controller="Home" asp-action="Index">return to lists</a>
    </form>
</div>

Lab18ConsumeApi/Views/ToDoList/DeleteDefault.cshtml
<div class="wrapper">
    <h2>Looks like you tried to delete the default list!</h2>
    <p>You need to keep that one!</p>

    <a asp-controller="Home" asp-action="Index">Return to lists</a>
</div>

Lab18ConsumeApi/Views/ToDoList/Details.cshtml
@model Lab18ConsumeApi.Models.ListsViewModel

<div class="wrapper">
    <h1>List: @Model.List.Name</h1>
    <form asp-action="Update" asp-route-id="@Model.List.ID">
        <table>
            <tr>
                <td>
                    <label asp-for="List.Name">Name</label>
                </td>
                <td>
                    <input asp-for="List.Name" />
                </td>
            </tr>
            <tr>
                <td>
                    <label asp-for="List.IsDone">Is it done?</label>
                </td>
                <td>
                    <input type="checkbox" asp-for="List.IsDone" />
                </td>
            </tr>
        </table>
        <button type="submit">Update list</button>
        <button asp-action="Delete" formmethod="get" asp-route-id="@Model.List.ID">Delete list</button>
        <a asp-controller="Home" asp-action="Index">return to lists</a>
    </form>
    <h2 style="display:block">Current Tasks in this list</h2>
    <table>
        @foreach (var item in Model.List.ToDoItems)
        {
            <tr>
                <td><h3>Task:</h3> @item.Name</td>
                <td><h3>Done:</h3> @item.IsDone</td>
            </tr>
        }
    </table>
</div>